spring.application.name=address
server.port = 8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

logging.level.com.deccan.address.client.employeeClient=DEBUG
logging.level.feign=DEBUG
spring.cloud.openfeign.client.config.default.loggerLevel=FULL


spring.mongodb.uri=mongodb://localhost:27017/address_db
