spring.application.name=address
server.port = 8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

logging.level.com.deccan.address.client.employeeClient=DEBUG
logging.level.feign=DEBUG
spring.cloud.openfeign.client.config.default.loggerLevel=FULL
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.alphanumeric-ids.enabled=true

resilience4j.circuitbreaker.instances.employeeClientgetEmployeeWithID.sliding-window-size=5
resilience4j.circuitbreaker.instances.employeeClientgetEmployeeWithID.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.employeeClientgetEmployeeWithID.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.employeeClientgetEmployeeWithID.wait-duration-in-open-state=10s


spring.mongodb.uri=mongodb://localhost:27017/address_db
