spring.application.name=employees
server.port=8083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

logging.level.com.deccan.employee.client.AddressClient=DEBUG
logging.level.feign=DEBUG
spring.cloud.openfeign.client.config.default.loggerLevel=FULL
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.alphanumeric-ids.enabled=true

resilience4j.circuitbreaker.instances.AddressClientsaveAddress.sliding-window-size=5
resilience4j.circuitbreaker.instances.AddressClientsaveAddress.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.AddressClientsaveAddress.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.AddressClientsaveAddress.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.AddressClientgetAddressesByEmployeeID.sliding-window-size=5
resilience4j.circuitbreaker.instances.AddressClientgetAddressesByEmployeeID.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.AddressClientgetAddressesByEmployeeID.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.AddressClientgetAddressesByEmployeeID.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.WorkLocationClientClientsaveWorkLocation.sliding-window-size=5
resilience4j.circuitbreaker.instances.WorkLocationClientClientsaveWorkLocation.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.WorkLocationClientClientsaveWorkLocation.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.WorkLocationClientClientsaveWorkLocation.wait-duration-in-open-state=10s


# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/employees
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: To specify a particular schema
# spring.datasource.url=jdbc:postgresql://localhost:5432/your_db?currentSchema=your_schema
